name: Slimefun
version: 4.1.16
author: The Slimefun 4 Community
description: Slimefun basically turns your entire Server into a FTB modpack without installing a single mod
website: http://TheBusyBiscuit.github.io/

main: me.mrCookieSlime.Slimefun.SlimefunStartup
softdepend: [CS-CoreLib, ClearLag, WorldEdit]

api-version: 1.13

commands:
  slimefun:
    description: 基础的Slimefun命令
    aliases: sf
    usage: /sf <argument>
permissions:
  slimefun.cheat.items:
    description: 允许你使用作弊获得物品
    default: op
  slimefun.cheat.researches:
    description: 允许你使用作弊获得成就
    default: op
  slimefun.stats.others:
    description: 允许你获得其他玩家的统计信息
    default: op
  slimefun.android.upload-script:
    description: 允许你上传Android脚本
    default: op
  slimefun.command.timings:
    description: 允许你使用/sf timings
    default: op
  slimefun.command.teleporter:
    description: 允许你使用/sf teleporter
    default: op
  slimefun.command.versions:
    description: 允许你使用/sf versions
    default: op
  slimefun.command.guide:
    description: 允许你获得Slimefun指南
    default: true
  slimefun.command.open_guide:
    description: 允许你不用书仍然可以打开指南界面
    default: op
  slimefun.android.bypass:
    description: 允许你更改其他玩家的Android
    default: op
  slimefun.cargo.bypass:
    description: 允许你更改其他玩家的货物方块
    default: op
  slimefun.inventory.bypass:
    description: 允许你使用所有的Slimefun机器
    default: op
